name: Bug Report
description: Report a problem in null-ls
labels: [bug]
body:

  - type: checkboxes
    id: faq-prerequisite
    attributes:
      label: FAQ
      options:
        - label: I have checked [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.
          required: true

  - type: checkboxes
    id: issue-prerequisite
    attributes:
      label: Issues
      options:
        - label: I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues) and there are no issues already open with the same problem.
          required: true

  - type: input
    attributes:
      label: "Neovim Version"
      description: "`nvim --version`:"
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Steps to reproduce"

  - type: textarea
    attributes:
      label: "Expected behavior"

  - type: textarea
    attributes:
      label: "Actual behavior"
      description: "A description of the behavior you expected. May optionally include logs, images, or videos."
