name: Bug Report
description: Report a problem in null-ls
labels: [bug]
body:
  - type: checkboxes
    id: faq-prerequisite
    attributes:
      label: FAQ
      options:
        - label: I have checked the [FAQ](https://github.com/jose-elias-alvarez/null-ls.nvim#faq) and it didn't resolve my problem.
          required: true

  - type: checkboxes
    id: issue-prerequisite
    attributes:
      label: Issues
      options:
        - label: I have checked [existing issues](https://github.com/jose-elias-alvarez/null-ls.nvim/issues?q=is%3Aissue) and there are no issues with the same problem.
          required: true

  - type: input
    attributes:
      label: "Neovim Version"
      description: "`nvim --version`:"
    validations:
      required: true

  - type: textarea
    attributes:
      label: "null-ls config"
      description: "The minimal configuration required to reproduce your bug. Do not post or link to your entire Neovim configuration!"
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Steps to reproduce"
      description: "Full reproduction steps. Include a sample file if your issue relates to a specific filetype."
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Expected behavior"
      description: "A description of the behavior you expected."
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Actual behavior"
      description: "A description of the actual behavior."
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Debug log"
      description: "Debug log output (see README for instructions)"
    validations:
      required: true

  - type: dropdown
    id: help
    attributes:
      label: "Help"
      description: "Would you be able to resolve this issue by submitting a pull request?"
      options:
        - "Yes"
        - "Yes, but I don't know how to start. I would need guidance"
        - "No"
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Implementation help"
      description: "If you selected yes in the last question please specify in detail what you would need help with in order to implement this."
    validations:
      required: false
