name: default

on: [pull_request]

jobs:
  stylua:
    name: Check codestyle
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: JohnnyMorganz/stylua-action@1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --color always --check .
  metadata-diff-check:
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v2
          - uses: rhysd/action-setup-vim@v1
            with:
              neovim: true
              version: nightly

          - name: Run autogen_metadata.sh script
            run: bash ./scripts/autogen_metadata.sh

          - name: check for updates
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              COMMIT_MSG: |
                ci(docgen): update metdata
                skip-checks: true
            run: |
              git config user.email "actions@github"
              git config user.name "Github Actions"
              git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
              git update-index --refresh
              # Only commit if we have changes
              git diff-index --quiet HEAD -- \
                || (git add --all ; git commit -m "${COMMIT_MSG}"; git push origin HEAD:${GITHUB_REF})
